export const SET_REG_ERRORS = 'SET_REG_ERRORS'
export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION'
export const CLEAR_REGISTRATION_ERRORS = 'CLEAR_REGISTRATION_ERRORS'
export const CLEAR_INPUT_CONTROLS = 'CLEAR_INPUT_CONTROLS'
export const REGISTRATION_LOADING_TRUE = 'REGISTRATION_LOADING_TRUE'
export const REGISTRATION_LOADING_FALSE = 'REGISTRATION_LOADING_FALSE'
export const REGISTRATION_FORM_VALID = 'REGISTRATION_FORM_VALID'
export const UPDATE_REGISTRATION_INPUTS = 'UPDATE_REGISTRATION_INPUTS'



export const CLEAR_ERRORS_EMAIL = 'REGISTRATION/CLEAR_ERRORS_EMAIL'
export const CLEAR_ERRORS_PASSWORD = 'REGISTRATION/CLEAR_ERRORS_PASSWORD'
export const CLEAR_ERRORS_NAME = 'REGISTRATION/CLEAR_ERRORS_NAME'