export const SET_LOGIN_DATA = 'SET_LOGIN_DATA'
export const LOG_OUT = 'LOG_OUT'
export const ADD_SOCKET_ID = 'ADD_SOCKET_ID'
export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS'
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS'
export const LOGIN_DATA_LOADING_TRUE = 'LOGIN_DATA_LOADING_TRUE'
export const LOGIN_DATA_LOADING_FALSE = 'LOGIN_DATA_LOADING_FALSE'
export const UPDATE_LOGIN_INPUT_CONTROLS_EMAIL = 'UPDATE_LOGIN_INPUT_CONTROLS_EMAIL'
export const UPDATE_LOGIN_INPUT_CONTROLS_PASSWORD = 'UPDATE_LOGIN_INPUT_CONTROLS_PASSWORD'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'







