export const SET_LOGIN_DATA = 'SET_LOGIN_DATA'
export const LOG_OUT = 'LOG_OUT'
export const ADD_SOCKET_ID = 'ADD_SOCKET_ID'
export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS'
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS'
export const UPDATE_LOGIN_INPUTS = 'UPDATE_LOGIN_INPUTS'
export const CLEAR_LOGIN_STATE = 'CLEAR_LOGIN_STATE'
export const REFRESH_DATA = 'REFRESH_DATA'
export const SET_SOCKET_CONNECTED_AND_ID = 'SET_SOCKET_CONNECTED_AND_ID'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_LOADING_TRUE = 'LOGIN_LOADING_TRUE'
export const LOGIN_LOADING_FALSE = 'LOGIN_LOADING_FALSE'
export const LOGIN_FORM_VALID = 'LOGIN_FORM_VALID'






