export const REFRESH_EVENTS = 'EVENTS/REFRESH_EVENTS'
export const EVENT_INPUT_FIELDS = "EVENT_INPUT_FIELDS"
export const CATEGORIES_FILTER = 'CATEGORIES_FILTER'
export const CLICKED_EVENT_CALENDAR = 'CLICKED_EVENT_CALENDAR'
export const CLEAR_ALL_ADD_EVENT_INPUTS = 'CLEAR_ALL_ADD_EVENT_INPUTS'
