export const DELETE_USER = 'PROFILE/DELETE_USER'
export const SET_ROLE = 'PROFILE/SET_ROLE'

export const GET_USERS = 'PROFILE/GET_USERS'
export const CLICK_RENDER_USERS = 'PROFILE/RENDER_GET_USERS'
export const CLICK_RENDER_EVENTS = 'PROFILE/GET_EVENTS'

export const CLICK_RENDER_CREATE_EVENT = 'CLICK/CREATE_EVENT'
export const RENDER_MODAL_CONTENT = 'RENDER_MODAL_CONTENT'
export const CLICK_RENDER_HOME_PAGE = 'CLICK_RENDER_HOME_PAGE'


export const PROFILE_PAGE_USERS_LOADING_TRUE = 'PROFILE_PAGE_USERS_LOADING_TRUE'
export const PROFILE_PAGE_USERS_LOADING_FALSE = 'PROFILE_PAGE_USERS_LOADING_FALSE'

export const PROFILE_PAGE_EVENTS_LOADING_TRUE = 'PROFILE_PAGE_EVENTS_LOADING_TRUE'
export const PROFILE_PAGE_EVENTS_LOADING_FALSE = 'PROFILE_PAGE_EVENTS_LOADING_FALSE'
export const PROFILE_PAGE_HOME_LOADING_TRUE = 'PROFILE_PAGE_HOME_LOADING_TRUE'
export const PROFILE_PAGE_HOME_LOADING_FALSE = 'PROFILE_PAGE_HOME_LOADING_FALSE'

export const PROFILE_PAGE_CREATE_EVENT_LOADING_TRUE = 'PROFILE_PAGE_CREATE_EVENT_LOADING_TRUE'
export const PROFILE_PAGE_CREATE_EVENT_LOADING_FALSE = 'PROFILE_PAGE_CREATE_EVENT_LOADING_FALSE'